### ISSUE TITLE
VS2017 WTL Dialog project have error at create

### ISSUE THREAD

**Issue by patton88** [allenk/WTL-Wizard-VS2017#2]
VS2017 WTLsdi have worked well. But, WTL Dialog project have error at create, it failed. Error:

Navigation failed. Cannot find
d:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\WTL-Wizard-VS2017\AppWiz\Files_15\HTML\1033\null.htm

**Comment by allenk** [comment]
I have fixed the issue. please sync your project and try again.

**Comment by patton88** [comment]
Thank you for your hard work.

**Comment by patton88** [comment]
Thank for fix ribbon bug:
                // atlribbon.h	422
		static void (CharFormat::*Getk_[])(IPropertyStore*) = 
		{
			&CharFormat::Getk_Family, 
			&CharFormat::Getk_FontProperties_Size, 
			////no instance of function template "WTL::RibbonUI::CharFormat::Getk_MaskEffect" matches the required type
			&CharFormat::Getk_MaskEffect<CFM_BOLD, CFE_BOLD, UI_PKEY_FontProperties_Bold>,
			&CharFormat::Getk_MaskEffect<CFM_ITALIC, CFE_ITALIC, UI_PKEY_FontProperties_Italic>,
			&CharFormat::Getk_MaskEffect<CFM_UNDERLINE, CFE_UNDERLINE, UI_PKEY_FontProperties_Underline>,
			&CharFormat::Getk_MaskEffect<CFM_STRIKEOUT, CFE_STRIKEOUT, UI_PKEY_FontProperties_Strikethrough>,
			////no instance of function template "WTL::RibbonUI::CharFormat::Getk_MaskEffect" matches the required type

			&CharFormat::Getk_VerticalPositioning, 

			////no instance of function template "WTL::RibbonUI::CharFormat::Getk_Color" matches the required type
			&CharFormat::Getk_Color<CFM_COLOR, UI_PKEY_FontProperties_ForegroundColor>, 
			&CharFormat::Getk_Color<CFM_BACKCOLOR, UI_PKEY_FontProperties_BackgroundColor>, 
			&CharFormat::Getk_ColorType<CFM_COLOR, CFE_AUTOCOLOR, UI_SWATCHCOLORTYPE_AUTOMATIC, UI_PKEY_FontProperties_ForegroundColorType>,
			&CharFormat::Getk_ColorType<CFM_BACKCOLOR, CFE_AUTOBACKCOLOR, UI_SWATCHCOLORTYPE_NOCOLOR, UI_PKEY_FontProperties_BackgroundColorType>,
			////no instance of function template "WTL::RibbonUI::CharFormat::Getk_Color" matches the required type
			
		};

**Comment by allenk** [comment]
Do you still suffer Ribbon issue? I had fix the issue in previous commit. Could you say more about the issue?

**Comment by patton88** [comment]
Thank you for your hard work. VS2017 WTL Ribbon project has already work well with version of "fix app wizard dialog based project error". Besides, You must copy Windows SDK 7.1A to d:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\, and add it  in project ExecutablePath directories.

--------------------------------------------------------------
Better way is fix config file. You may add content to file of 
"%USERPROFILE%\AppData\Local\Microsoft\MSBuild\v4.0\Microsoft.Cpp.Win32.user.props".

You add the below content to end of file, before  `</Project>`

 ` <PropertyGroup>`
        `<IncludePath>$(VCInstallDir)\WTL\include;$(IncludePath)</IncludePath>`
        `<ExecutablePath>%ProgramFiles(x86)%\Microsoft SDKs\Windows\v7.1A\Bin\;$(ExecutablePath)</ExecutablePath>`
`</PropertyGroup>`

**Comment by allenk** [comment]
I think this might not a good way to add 7.1a bin in MSBuild prop.
We have use SdkVer.h to configure the SDK toolkits. You may consider to change the SDK in your project configuration. SDK version should not be kept in MSBuild or you may suffer problems if you are not using SDK 7.1a in other project.

**Comment by patton88** [comment]
Yes, each has its advantages and disadvantages.

**Comment by patton88** [comment]
In VS2017, how can I let WTL create project auto with the highest SDK 10.0.14393.0, rather than SDK 8.1?

Thanks in advance!
  ----- Original Message -----

**Comment by allenk** [comment]
Actually, I have no idea how to generate the project with your preferred SDK. In old SDK, the wizard uses custom project create function to generate the project. Unfortunately, it doesn't work with VS 2017. In my own branch, I use built-in project function to generate the project and solution files. I think it's possible to do more if we can study more about new design in VS 2017 wizard engine.

**Comment by patton88** [comment]
I have found a temporary way that let WTL create project auto with the highest SDK 10.0.14393.0, rather than SDK 8.1.

To modify below file content in two 8.1 to 10.0.14393.0
%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.props

The WTL project compile and run well. But the project Property Pages | General | Windows SDK Version is empty.
