### ISSUE TITLE
NewStyles.css vs styles.css in the wizard

### ISSUE THREAD

**Issue by joyride9999** [allenk/WTL-Wizard-VS2017#3]
Hi there,
nice work porting it to vs2017, just a quick fix because the wizard is still crashing at some js error. In AppType.htm and default.htm, line "strURL += "/Newstyles.css" should be strURL += "/styles.css" as there is no newstyles.css in WTL :/ .... but maybe i'm missing something.

**Comment by joyride9999** [comment]
or just a hackish solution for vs2017 copy newstyles.css to the same folder where styles.css resides in wtl folder

**Comment by allenk** [comment]
I have committed the update. Could you have a try for this update?
Actually, it's a very old WTL bug (I think). After changing it to style.css, I see a new page while you run WTL wizard. It's just a simple README something and then press 'Next'... everything is the same.
It's pity that the WTL is already too old to catch modern design. If you run MFC wizard, you see lots new features. I hope WTL could follow up the steps of VC/MFC but it would be hard.

**Comment by joyride9999** [comment]
yes it's an old bug, ill give a look later this evening, i'll try to fix the vbscript that installs it, shouldn't be to hard, but i didn't use vbscript for quite some time :)

**Comment by joyride9999** [comment]
Hey again, i think i got to the bottom of it, so the real issue was this line 
"var strCommonPath = strPath + "/Common.js";" which should be replaced with 
"var strCommonPath = strPath + "/common.js";   for default.htm, AppType.htm, and UIFeatures.htm   ... as it seems it's case sensitive

This in turn will make the previous change absolete -> strURL += "/NewStyles.css";  should work again  (sorry for not getting on first try though :)

**Comment by joyride9999** [comment]
ps : i would suggest to make the change just for files_15 folder as i don't know how far back the bug goes :(

**Comment by allenk** [comment]
I have reviewed again with your suggestions. Yes, it seems to work if we change the Common.js to common.js. I have no idea that how can be a case sensitive issue.
Besides, I also upload my new ARTWORK for WTL :P. I am not good at ARTWORK.
Just use Microsoft 's new 3D paint to create 3 cubes and adds WTL words :P
